### ISSUE TITLE
测试3

### ISSUE THREAD

**Issue by wangyunlai615** [hnwyllmm/snip#17]
测试

**Comment by hnwyllmm** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Test

**Comment by wangyunlai615** [comment]
测试comment

**Comment by hnwyllmm** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Test comment
